### ISSUE TITLE
Проблемы с Topic()

### ISSUE THREAD

**Issue by OdSt** [VigilSS13/Vigil#34]
По неизвестной нам причине в некоторых местах не вызывается прок Topic()
Почему - богу единому известно.
Где есть проблемы:
- Синтезатор эдитора
- Блендер химический

**Comment by EditorRUS** [comment]
У меня в синтезаторе Topic таки вызывался, но из-за того, что world << msg ничего не делает у меня создалось впечатление, что оно не работало.

Конкретно у меня проблема была вызвана использованием canUseTopic(), которая не работает (больше), но тем не менее осталась в билде.

**Comment by OdSt** [comment]
Это радует

**Comment by Viol** [comment]
Обновил nanoUI до ВГшевского. Проблема с топиком решена.
