### ISSUE TITLE
Повысить радиус лимиток

### ISSUE THREAD

**Issue by OdSt** [VigilSS13/Vigil#39]
Повышать или не повышать?
Дело в том, что лимитки у нас нормально взрываются даже из говна и палок, но в обмен на это у них маленький радиус

**Comment by Viol** [comment]
Повысил радиус до ТГшного. Нет, если собрать бомбу при помощи нехитрых приспособлений, больше 3,7,14 она не будет. Для доведения до ТГшного капа нужна импровизация.
