### ISSUE TITLE
Баг с ПДА

### ISSUE THREAD

**Issue by OdSt** [VigilSS13/Vigil#53]
В пда есть великая проблема
Буква я-то в сообщения обрабатывается, все ок
Никаких багов при показе
НО ПРИ ОТПРАВКЕ СООБЩЕНИЙ С я на конце
ПДА начинает думать, что мы хотим отослать еще одно сообщение ибо я заменяется на перенос строки

**Comment by Viol** [comment]
Связано с обработкой бйондом #255. В условиях обмазывания HTML'ем и encode/decode нерешаемо. Ставьте точки в конце сообщений.
